---
- name: install apache on CentOS
  package: 
    name: httpd
    state: present

- name: allow httpd throught firewall
  firewalld:
    port: 80/tcp
    permanent: true
    state: disabled
  notify:
    - restart firewall 

 
- name: ensure apache is running
  service:
    name: httpd 
    state: started 
    enabled: yes
